### ISSUE TITLE
Group assignment and release notes stopped working

### ISSUE THREAD

**Issue by olivierbrand** [fastlane/fastlane-plugin-firebase_app_distribution#176]
Our Fastlane script was auto assigning groups of users and adding some release notes but it stopped working a few days ago. Updated to latest plugin yesterday but still not working. Are you aware of any issues or changes in relation to this issue?

**Comment by rachaprince** [comment]
Hi olivierbrand! Thanks for reaching out.

A couple of questions to help us debug:
* What is the exact failure case you are experiencing? Are there any error messages you are receiving? Or is the request succeeding, but something is not functioning as expected?
* Could you send us your fastfile? Please be sure not to include anything sensitive

**Comment by olivierbrand** [comment]
There are no errors as you can see below in our CI.
![image](https://user-images.githubusercontent.com/37886981/98386374-5523b800-200d-11eb-8a9c-aa53c963c50a.png)

Also attaching the Fastfile.

[Fastfile.zip](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/files/5502170/Fastfile.zip)

**Comment by rachaprince** [comment]
Thanks!

A couple of follow-up questions:
* When was the last time that this worked successfully for you? And the first date and time it stopped working? 
* Can you describe the change in behavior you saw?

**Comment by olivierbrand** [comment]
October 30th was the last time it worked. See image below

![image](https://user-images.githubusercontent.com/37886981/98390129-32e06900-2012-11eb-9498-525a8c6f106b.png)

And build that failed was issued Nov 2nd:

![image](https://user-images.githubusercontent.com/37886981/98390308-67542500-2012-11eb-9a86-1a5f4e50ca03.png)

**Comment by rachaprince** [comment]
Hi olivierbrand, 

We recently made some changes in our backend that may have impacted this, but we reverted the change earlier this morning. Could you try again, and let us know if you still run into the same issue?

If it still doesn't work, another thing to try is to lowercase the group name to "development" instead of "Development". It looks like your fastfile is passing in the group name, instead of the group alias. The group alias can be found on the Testers & Group tab (see the screen shot below). The group alias should be used for cli tools    

![image](https://user-images.githubusercontent.com/7172296/98392959-a2605380-2026-11eb-8dad-b1319db8e5eb.png)

**Comment by olivierbrand** [comment]
Using alias vs names did not help, result is the same.
Where do I need to add the debug flag? I have added it to:
`firebase_app_distribution(
    debug: true,`
I do not get any additional info in my CI

**Comment by tonybaroneee** [comment]
Glad to hear @olivierbrand!

**Comment by Aisalkyn** [comment]
The issue is still actual. Re-installation of the plugin did not help me :(

**Comment by Aisalkyn** [comment]
@tonybaroneee i was on version 0.2.0.  and debug is already set for true. Now will try to update for 0.2.4 and check. Thank you!

**Comment by Aisalkyn** [comment]
It helped me!
The updating of _fastlane-plugin-firebase_app_distribution_ version to (0.2.4) helped me. Thank you!

**Comment by tonybaroneee** [comment]
@Aisalkyn Glad to hear, you're welcome!
