### ISSUE TITLE
release_notes and release_notes_file not working at the same time

### ISSUE THREAD

**Issue by yildirimatcioglu** [fastlane/fastlane-plugin-firebase_app_distribution#185]
### Issue Description
release_notes and release_notes_file not working at the same time,
 I want to add this two as one notes. How can I do that?

**Comment by tagboola** [comment]
Hi @yildirimatcioglu. This is actually working as expected: If the `release_notes` path is passed we use it, otherwise we use the value of `release_notes_file` and read the release notes from the file.

To add them both, maybe you can add a step before the `firebase_app_distribution` action that concatenates them both in a file and then pass the path to the file in the `release_notes_file` param.
