### ISSUE TITLE
Plugin doesn't use release notes file when explicitly told to do so

### ISSUE THREAD

**Issue by xrdrx** [fastlane/fastlane-plugin-firebase_app_distribution#195]
### Issue Description
Plugin doesn't use release notes file when explicitly told to do so.

Steps to reproduce:
1. set lane_context[SharedValues::FL_CHANGELOG] to some value
2. try to call firebase_app_distribution passing release_notes_file

It takes lane_context[SharedValues::FL_CHANGELOG] as default:
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/2562e8ec0751f38f993f517219bf7fe0fb1e95d4/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb#L220
And doesn't even look at passed file:
https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/blob/2562e8ec0751f38f993f517219bf7fe0fb1e95d4/lib/fastlane/plugin/firebase_app_distribution/helper/firebase_app_distribution_helper.rb#L17

##### Configuration
app: app
firebase_cli_token: token
release_notes_file: path_to_file

**Comment by lfkellogg** [comment]
@xrdrx Thanks for the detailed report! This has been fixed in https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/196 and will go out with the next release. If you'd like to pick up the fix now it's available in the prerelease, which you can get by updating your `fastlane/Pluginfile` to include:

```
gem 'fastlane-plugin-firebase_app_distribution', '0.2.7.pre.2'
```

**Comment by xrdrx** [comment]
Cool, thanks!
