### ISSUE TITLE
Fetch most recent version code from App Distribution

### ISSUE THREAD

**Issue by db-dblank** [fastlane/fastlane-plugin-firebase_app_distribution#25]
It would be nice if we could fetch the most recent version code from App Distribution so every time we upload a new APK we increment the version code based on the latest uploaded build.

The same feature as [latest_testflight_build_number](https://docs.fastlane.tools/actions/latest_testflight_build_number).

For iOS we can use this way:
`increment_build_number(build_number: latest_testflight_build_number + 1)`

Then for Android we could do this:
`increment_version_code(version_code: latest_app_distribution_version_code + 1)`

**Comment by kevinkokomani** [comment]
Thanks for your feature request @db-dblank! I'm marking this down for the team to review and prioritize.

**Comment by timMorrill** [comment]
+1 on this. This would help immensely.

**Comment by jb2b38** [comment]
+1, and maybe add an option to delete a previously uploaded version for when you want to close tests for obsolete beta distributions.

**Comment by MichealNguyen1** [comment]
+1 on this. Would be really helpful.

**Comment by Neo1083** [comment]
+1 on this

**Comment by MichealNguyen1** [comment]
I am using a workaround for now. My project is using CircleCI, and my configuration is automatically triggered build when pushed a new commit. Here is my lane:

```
desc "Increment build number"
lane :increment_build_number_lane do 
    latestBuildNumber = get_build_number(xcodeproj: "Driver.xcodeproj")
    newBuildNumber = ((latestBuildNumber.is_a? String) ? latestBuildNumber.to_i : latestBuildNumber) + 1
    increment_build_number(build_number: newBuildNumber)
 end
```

Hope it would help someone.

**Comment by joeyfigaro** [comment]
Also requesting that support for this be added.

**Comment by nazrdogan** [comment]
+1

**Comment by cyhn1520** [comment]
+1

**Comment by teriologia** [comment]
+1

**Comment by Luckygirlllll** [comment]
I also would like to have this feature!

**Comment by Niko-r** [comment]
+1

**Comment by rompl1** [comment]
+1

**Comment by MichealNguyen1** [comment]
If someone is using CircleCI and looking for a workaround, I think you should consider this environment variable: 
CIRCLE_BUILD_NUM

**Comment by awaisiosdev** [comment]
+1. That would be really helpful.

**Comment by joeyfigaro** [comment]
Who can we ping/get ahold of for this?

**Comment by liat-google** [comment]
Hi there,
Liat here - Product Manager for Firebase App Distribution. 
I'm excited to share that our team is working on a public API, that would provide an easy way to fetch versions codes (which can be sorted to get the latest).
We love hearing from our customers, so please feel free to submit future feature requests via Firebase customer support.
Best regards,
Liat

**Comment by airowe-ra** [comment]
@liat-google Any update on the progress here?

**Comment by vtn1508** [comment]
+1

**Comment by obhserge** [comment]
Getting 403 error. 
[16:50:08]: the server responded with status 403

**Comment by Dirklectisch** [comment]
@lfkellogg A tried out the pre release version but could not get it to work. Here's the error I'm getting.

```
bundler: failed to load command: fastlane (/Users/dirklectisch/.rvm/gems/ruby-3.0.0/bin/fastlane)
/Users/dirklectisch/.rvm/gems/ruby-3.0.0/gems/faraday-1.8.0/lib/faraday/response/raise_error.rb:20:in `on_complete': \e[31m[!] the server responded with status 403\e[0m (Faraday::ForbiddenError)
```

Seems like authentication is failing. I have tried both authentication with the `$FIREBASE_TOKEN` and the service account json. Both end with this exact error.

Thanks for the your effort getting this done. Let me know if there is any other information you need.

**Comment by mrtnrst** [comment]
@obhserge @Dirklectisch I can correctly fetch using the `service_credentials_file` option for the action. I'm running this in Github Actions on [`ubuntu-latest`](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) with Fastlane `2.198.1`.

```shell
[23:45:05]: ----------------------------------------------------------
[23:45:05]: Authenticating with --service_credentials_file path parameter: ******.json
[23:45:05]: 🔐 Authenticated successfully.
[23:45:05]: ⏳ Fetching latest release for app ***...
[23:45:06]: ✅ Latest release fetched successfully. Returning release and setting Actions.lane_context[:FIREBASE_APP_DISTRO_LATEST_RELEASE].
```

Possible the service account you used is not authorized to access the resource?

**Comment by lfkellogg** [comment]
@obhserge @Dirklectisch Sorry for the trouble, and thanks for trying this out.

As @mrtnrst points out, the error is likely due to a mismatch between the account you're using and the Firebase app. Can you please double check that the `app` parameter is correct, and that the account has access it? The logs should have a line starting with "Authenticating with..." or "No authentication method specified..." which should help clarify which account is being used.

If that's all correct and you're still getting a 403, the best way for me to help troubleshoot would be to get some info about your account and project. If you wouldn't mind, please reach out to me directly, ideally on [Firebase community Slack](https://firebase.community/) (my username is "Lee Kellogg") or by email at lkellogg@google.com.

**Comment by bombillazo** [comment]
This feature would greatly simplify app version management!! :D

**Comment by dandre-hound** [comment]
We are able to use this plugin locally, but we also receive a 403 when running in CI:
```
[21:20:28]: ----------------------------------------------------------
[21:20:28]: --- Step: firebase_app_distribution_get_latest_release ---
[21:20:28]: ----------------------------------------------------------
[21:20:28]: Authenticating with --service_credentials_file path parameter: fastlane/firebase_app_distribution_keys/dev2_firebase_key.json
[21:20:28]: 🔐 Authenticated successfully.
[21:20:28]: ⏳ Fetching latest release for app 1:***:android:<SCRUBBED>...
```
Authentication is successful, but `the server responded with status 403` is returned. Is there any logging we can enable to help further?

**Comment by rebehe** [comment]
Hi @dandre-hound, eng on App Distribution here. Unfortunately no additional logs are available, since 403 permission errors are sensitive information. My recommendation would be to verify that `fastlane/firebase_app_distribution_keys/dev2_firebase_key.json` is a service credentials file and that it matches the app that you're using it for.

**Comment by dandre-hound** [comment]
Thanks -- you're right, we had linked the wrong google cloud project to our firebase app. What helped us uncover this was going to Firebase project > settings > service accounts and clicking the service accounts link. This led us to the correct project which we then enabled the firebase app distribution service role and downloaded the right json key.

**Comment by franparamo87** [comment]
Hi @lfkellogg 
I have tested your function, and it has worked correctly returning the data from the last upload. Could we put a version string as an optional parameter in the call to obtain the information of the last upload of this version that is passed?
Thanks

**Comment by lfkellogg** [comment]
@franparamo87 Thanks so much for trying it out. A parameter to filter by version is a great idea! [The API](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.apps.releases/list#query-parameters) only supports filtering by release notes and creation time right now, so that would have to be added first. I've recorded a feature request.

**Comment by lfkellogg** [comment]
The `firebase_app_distribution_get_latest_release` action is available in the latest version, 0.3.2. More info the [release notes](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.3.2).

Thanks again for the feedback, everyone!

**Comment by saranjith-pk** [comment]
How to get the latest build number for a specific version?

**Comment by SYWTech-hub** [comment]
Thanks for this new feature! Can the version number returned by firebase_app_distribution_get_latest_release be set to circleci environment variable? So that it can be used in config.yml file?

**Comment by kaibolay** [comment]
> Thanks for this new feature! Can the version number returned by firebase_app_distribution_get_latest_release be set to circleci environment variable? So that it can be used in config.yml file?

Maybe something like this (untested):

```
lane :bump_version do
  latest_release = firebase_app_distribution_get_latest_release(
    app: "<your Firebase app ID>"
  )
  ENV["CIRCLE_BUILD_NUM"] = latest_release[:buildVersion].to_i + 1
end
```

**Comment by SYWTech-hub** [comment]
Thanks for the response! Since CIRCLE_BUILD_NUM is a predefined circleci variable, I don't want to overwrite
the build number value. So I defined my own variable and tried this in fastlane:

ENV["LATEST_APP_BUILD_NUM"] = latest_release[:buildVersion]

When I try to print it in config.yml like this: echo "LATEST_APP_BUILD_NUM: ${LATEST_APP_BUILD_NUM}", it prints it's initial 
value, not the actual App Build Number

Some more info on this:

When I run this command directly in the terminal:  

bundle exec fastlane get_latest_version

It returns this message:

Fetching latest release for app 1:XXXXXXXXXXX7:android:XXXXXXXXXXXXX2...
[13:40:30]: ✅ Latest release fetched successfully. Returning release and setting 
Actions.lane_context[:FIREBASE_APP_DISTRO_LATEST_RELEASE].

And in my config.yml, I have this code:

bundle exec fastlane get_latest_version
LATEST_APP_BUILD_NUM=${FASTLANE_FIREBASE_APP_DISTRO_LATEST_RELEASE}
echo "LATEST_APP_BUILD_NUM: ${LATEST_APP_BUILD_NUM}"

As the fastlane command is putting the result in the variable: FIREBASE_APP_DISTRO_LATEST_RELEASE

And as per this documentation:

https://docs.fastlane.tools/advanced/lanes/#lane-properties

FIREBASE_APP_DISTRO_LATEST_RELEASE is available as FASTLANE_FIREBASE_APP_DISTRO_LATEST_RELEASE, so I should be able
to access it in config.yml as ${FASTLANE_FIREBASE_APP_DISTRO_LATEST_RELEASE}

But echo "LATEST_APP_BUILD_NUM: ${LATEST_APP_BUILD_NUM}"  is not printing anything

**Comment by fahmisdk6** [comment]
> How to get the latest build number for a specific version?

+1

**Comment by brilliantinsane** [comment]
firebase_app_distribution_get_latest_release will fail if it is the first release/build. Shouldn't it just return 1 if there are no releases/builds currently?

**Comment by kaibolay** [comment]
> firebase_app_distribution_get_latest_release will fail if it is the first release/build. Shouldn't it just return 1 if there are no releases/builds currently?

It shouldn't fail. The [code](https://github.com/firebase/fastlane-plugin-firebase_app_distribution/blob/83d616c212be976c011bdfc6e613f5ff92933787/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_get_latest_release.rb#L37) is supposed to return `nil` if there are no releases.

You should be able to detect this and treat it any way you prefer (e.g. like `1`).
