### ISSUE TITLE
Downloaded firebase_app_distribution, but there is no firebase_app_distribution_login as an action.

### ISSUE THREAD

**Issue by tndus77** [fastlane/fastlane-plugin-firebase_app_distribution#304]
### *** Steps to file a bug ***
1. Try updating to the latest version of [this plugin](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases), and [fastlane](https://github.com/fastlane/fastlane/releases)
2. If the issue persists, fill out the sections below
3. Delete this section and submit

### Issue Description

I downloaded firebase_app_distribution, but there is no firebase_app_distribution_login as an action.
> screenshot
![스크린샷 2023-03-08 오후 5 39 47](https://user-images.githubusercontent.com/77282190/223665110-2e5c273b-ef1e-460d-aa46-f3f15a92b371.png)
##### Environment

| Library     | Version |
| fastlane-plugin-firebase_app_distribution | 0.5.0 |
| fastlane | [REPLACE WITH FASTLANE VERSION] |
| fastlane-plugin-firebase_app_distribution | [REPLACE WITH PLUGIN VERSION] |

**Comment by tndus77** [comment]
i downloaded firebase cli, too.

**Comment by tagboola** [comment]
Hi @tndus77,

This is actually working as expected. The `firebase_app_distribution_login` action has been deprecated since July 2022 and was recently removed in the [v0.5.0](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.5.0) release. See the [Distribute apps using to testers using fastlane](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#authenticate) documentation for alternative ways to login. Since you also downloaded it [signing in using the Firebase CLI](https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#cli-fastlane) may be easiest way.

**Comment by tagboola** [comment]
Feel free to re-open this bug if you have any other questions/concerns/feedback.

**Comment by colejd** [comment]
@tagboola, the docs [here](https://firebase.google.com/codelabs/appdistribution-udid-collection#3) are out of date - under "Authenticate your Firebase project", it asks the user to use `firebase_app_distribution_login`. This is confusing because the command is no longer available. Can you please pass this along?

**Comment by lfkellogg** [comment]
@colejd I've filed a bug with the team, thanks for the heads up.
